import { Home, Assignment, Receipt, Payment, CreditCard, TrendingUp, AccountBalance } from "@mui/icons-material"
import type { Account, NavigationItem, Transaction } from "@/types"

export const ACCOUNTS: Account[] = [
  { id: "credit-card", name: "Credit Card", balance: "", type: "credit" },
  { id: "treasury", name: "Treasury", balance: "$200,000.00", type: "treasury" },
  { id: "ops-payroll", name: "Ops / Payroll", balance: "$2,023,287.12", type: "ops" },
  { id: "ap", name: "AP", balance: "$226,767.82", type: "ap" },
  { id: "ar", name: "AR", balance: "$0.00", type: "ar" },
  { id: "checking", name: "Checking", balance: "$1,374,471.14", type: "checking", accountNumber: "0297" },
  { id: "savings", name: "Savings", balance: "$1,320,201.00", type: "savings", accountNumber: "7658" },
]

export const NAVIGATION_ITEMS: NavigationItem[] = [
  {
    id: "home",
    name: "Home",
    href: "/",
    icon: Home,
  },
  {
    id: "tasks",
    name: "Tasks",
    href: "/tasks",
    badge: "5",
    icon: Assignment,
  },
  {
    id: "transactions",
    name: "Transactions",
    href: "/transactions",
    isActive: true,
    icon: Receipt,
  },
  {
    id: "payments",
    name: "Payments",
    href: "/payments",
    hasSubmenu: true,
    icon: Payment,
  },
  {
    id: "cards",
    name: "Cards",
    href: "/cards",
    icon: CreditCard,
  },
  {
    id: "capital",
    name: "Capital",
    href: "/capital",
    icon: TrendingUp,
  },
  {
    id: "accounts",
    name: "Accounts",
    href: "/accounts",
    hasSubmenu: true,
    icon: AccountBalance,
  },
]

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "1",
    date: "Dec 6",
    merchant: "To Ops / Payroll",
    amount: -54810.16,
    account: "AR",
    paymentMethod: "Transfer",
    icon: "$",
    iconBg: "#f3f4f6",
    type: "transfer",
  },
  {
    id: "2",
    date: "",
    merchant: "From AR",
    amount: 54810.16,
    account: "Ops / Payroll",
    paymentMethod: "Transfer",
    icon: "$",
    iconBg: "#f3f4f6",
    type: "transfer",
  },
  {
    id: "3",
    date: "Dec 5",
    merchant: "Lily's Eatery",
    amount: 0.93,
    account: "Ops / Payroll",
    paymentMethod: "Jane B. • 1234",
    icon: "LE",
    iconBg: "#dbeafe",
    type: "payment",
  },
  {
    id: "4",
    date: "",
    merchant: "Deli 77",
    amount: 6.91,
    account: "Credit account",
    paymentMethod: "Jane B. • 5555",
    icon: "D7",
    iconBg: "#e9d5ff",
    type: "payment",
  },
  {
    id: "5",
    date: "",
    merchant: "Deli 77",
    amount: 23.28,
    account: "Ops / Payroll",
    paymentMethod: "Landon S. • 4923",
    icon: "D7",
    iconBg: "#e9d5ff",
    type: "payment",
  },
  {
    id: "6",
    date: "",
    merchant: "Office Stop Co.",
    amount: -287.89,
    account: "Ops / Payroll",
    paymentMethod: "Jessica A. • 9921",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment",
  },
  {
    id: "7",
    date: "",
    merchant: "Trader John's",
    amount: 53.49,
    account: "Credit account",
    paymentMethod: "Landon S. • 0331",
    icon: "TJ",
    iconBg: "#fee2e2",
    type: "payment",
  },
  {
    id: "8",
    date: "",
    merchant: "Office Stop Co.",
    amount: -662.7,
    account: "Credit account",
    paymentMethod: "Jane B. • 0330",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment",
  },
  {
    id: "9",
    date: "",
    merchant: "Office Stop Co.",
    amount: 563.94,
    account: "Credit account",
    paymentMethod: "Jane B. • 0330",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment",
  },
  {
    id: "10",
    date: "",
    merchant: "The Plant Organic Cafe",
    amount: -14.21,
    account: "Ops / Payroll",
    paymentMethod: "Jane B. • 4928",
    icon: "P",
    iconBg: "#dcfce7",
    type: "payment",
  },
  {
    id: "11",
    date: "",
    merchant: "Trader John's",
    amount: -11.82,
    account: "Ops / Payroll",
    paymentMethod: "Jane B. • 3745",
    icon: "TJ",
    iconBg: "#fee2e2",
    type: "payment",
  },
  {
    id: "12",
    date: "",
    merchant: "Milgram Brokerage",
    amount: 2760.75,
    account: "Ops / Payroll",
    paymentMethod: "Jane B. • 2345",
    icon: "MB",
    iconBg: "#e9d5ff",
    type: "payment",
  },
  {
    id: "13",
    date: "",
    merchant: "Monarch Books",
    amount: 49.36,
    account: "Ops / Payroll",
    paymentMethod: "Aluna T. • 7840",
    icon: "MB",
    iconBg: "#e9d5ff",
    type: "payment",
  },
]
