import { Home, Assignment, Receipt, Payment, CreditCard, TrendingUp, AccountBalance } from "@mui/icons-material"
import type { Account, Column, NavigationItem, Transaction } from "@/types"

export const ACCOUNTS: Account[] = [
  { id: "credit-card", name: "Credit Card", balance: "", type: "credit" },
  { id: "treasury", name: "Treasury", balance: "$200,000.00", type: "treasury" },
  { id: "ops-payroll", name: "Ops / Payroll", balance: "$2,023,287.12", type: "ops" },
  { id: "ap", name: "AP", balance: "$226,767.82", type: "ap" },
  { id: "ar", name: "AR", balance: "$0.00", type: "ar" },
  { id: "checking", name: "Checking", balance: "$1,374,471.14", type: "checking", accountNumber: "0297" },
  { id: "savings", name: "Savings", balance: "$1,320,201.00", type: "savings", accountNumber: "7658" },
]

export const NAVIGATION_ITEMS: NavigationItem[] = [
  {
    id: "home",
    name: "Home",
    href: "/",
    icon: Home,
  },
  {
    id: "tasks",
    name: "Tasks",
    href: "/tasks",
    badge: "5",
    icon: Assignment,
  },
  {
    id: "transactions",
    name: "Transactions",
    href: "/transactions",
    isActive: true,
    icon: Receipt,
  },
  {
    id: "payments",
    name: "Payments",
    href: "/payments",
    hasSubmenu: true,
    icon: Payment,
  },
  {
    id: "cards",
    name: "Cards",
    href: "/cards",
    icon: CreditCard,
  },
  {
    id: "capital",
    name: "Capital",
    href: "/capital",
    icon: TrendingUp,
  },
  {
    id: "accounts",
    name: "Accounts",
    href: "/accounts",
    hasSubmenu: true,
    icon: AccountBalance,
  },
]

export const TRANSACTION_COLUMNS: Column[] = [
  { label: "Date", subText: "(GMT+8:30)", styles: { width: "12%" } },
  { label: "To/From", styles: { width: "20%" } },
  { label: "Amount", styles: { width: "15%", textAlign: 'right' } },
  { label: "Account", styles: { width: "15%" } },
  {
    label: "Method",
    tooltipText: "This is a Placeholder tooltip text",
    styles: { width: "20%" },
  },
  { label: "GL Code", styles: { width: "14%" } },
  { label: "Attachment", styles: { width: "3%", textAlign: 'right' } },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  // First 15 records - 25th May
  {
    id: "1",
    date: new Date("2025-05-25T10:30:00"),
    merchant: "To Ops / Payroll",
    amount: -54810.16,
    account: "AR",
    paymentMethod: "Transfer",
    icon: "$",
    iconBg: "#f3f4f6",
    type: "transfer" as const,
    currency: "USD",
  },
  {
    id: "2",
    date: new Date("2025-05-25T14:45:00"),
    merchant: "From AR",
    amount: 54810.16,
    account: "Ops / Payroll",
    paymentMethod: "Transfer",
    icon: "$",
    iconBg: "#f3f4f6",
    type: "transfer" as const,
    currency: "USD",
  },
  {
    id: "3",
    date: new Date("2025-05-25T09:15:00"),
    merchant: "Lily's Eatery",
    amount: 0.93,
    account: "Ops / Payroll",
    paymentMethod: "Jane B. • 1234",
    icon: "LE",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "4",
    date: new Date("2025-05-25T16:00:00"),
    merchant: "Deli 77",
    amount: 6.91,
    account: "Credit account",
    paymentMethod: "Jane B. • 5555",
    icon: "D7",
    iconBg: "#e9d5ff",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "5",
    date: new Date("2025-05-25T17:30:00"),
    merchant: "Deli 77",
    amount: 23.28,
    account: "Ops / Payroll",
    paymentMethod: "Landon S. • 4923",
    icon: "D7",
    iconBg: "#e9d5ff",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "6",
    date: new Date("2025-05-25T11:00:00"),
    merchant: "Office Stop Co.",
    amount: -287.89,
    account: "Ops / Payroll",
    paymentMethod: "Jessica A. • 9921",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "7",
    date: new Date("2025-05-25T13:00:00"),
    merchant: "Trader John's",
    amount: 53.49,
    account: "Credit account",
    paymentMethod: "Landon S. • 0331",
    icon: "TJ",
    iconBg: "#fee2e2",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "8",
    date: new Date("2025-05-25T15:30:00"),
    merchant: "Office Stop Co.",
    amount: -662.7,
    account: "Credit account",
    paymentMethod: "Jane B. • 0330",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "9",
    date: new Date("2025-05-25T17:00:00"),
    merchant: "Office Stop Co.",
    amount: 563.94,
    account: "Credit account",
    paymentMethod: "Jane B. • 0330",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "10",
    date: new Date("2025-05-25T12:00:00"),
    merchant: "The Plant Organic Cafe",
    amount: -14.21,
    account: "Ops / Payroll",
    paymentMethod: "Jane B. • 4928",
    icon: "P",
    iconBg: "#dcfce7",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "11",
    date: new Date("2025-05-25T10:30:00"),
    merchant: "To Ops / Payroll",
    amount: -54810.16,
    account: "AR",
    paymentMethod: "Transfer",
    icon: "$",
    iconBg: "#f3f4f6",
    type: "transfer" as const,
    currency: "USD",
  },
  {
    id: "12",
    date: new Date("2025-05-25T14:45:00"),
    merchant: "From AR",
    amount: 54810.16,
    account: "Ops / Payroll",
    paymentMethod: "Transfer",
    icon: "$",
    iconBg: "#f3f4f6",
    type: "transfer" as const,
    currency: "USD",
  },
  {
    id: "13",
    date: new Date("2025-05-25T09:15:00"),
    merchant: "Lily's Eatery",
    amount: 0.93,
    account: "Ops / Payroll",
    paymentMethod: "Jane B. • 1234",
    icon: "LE",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "14",
    date: new Date("2025-05-25T16:00:00"),
    merchant: "Deli 77",
    amount: 6.91,
    account: "Credit account",
    paymentMethod: "Jane B. • 5555",
    icon: "D7",
    iconBg: "#e9d5ff",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "15",
    date: new Date("2025-05-25T17:30:00"),
    merchant: "Deli 77",
    amount: 23.28,
    account: "Ops / Payroll",
    paymentMethod: "Landon S. • 4923",
    icon: "D7",
    iconBg: "#e9d5ff",
    type: "payment" as const,
    currency: "USD",
  },
  // Next 7 records - 24th May
  {
    id: "16",
    date: new Date("2025-05-24T11:00:00"),
    merchant: "Office Stop Co.",
    amount: -287.89,
    account: "Ops / Payroll",
    paymentMethod: "Jessica A. • 9921",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "17",
    date: new Date("2025-05-24T13:00:00"),
    merchant: "Trader John's",
    amount: 53.49,
    account: "Credit account",
    paymentMethod: "Landon S. • 0331",
    icon: "TJ",
    iconBg: "#fee2e2",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "18",
    date: new Date("2025-05-24T15:30:00"),
    merchant: "Office Stop Co.",
    amount: -662.7,
    account: "Credit account",
    paymentMethod: "Jane B. • 0330",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "19",
    date: new Date("2025-05-24T17:00:00"),
    merchant: "Office Stop Co.",
    amount: 563.94,
    account: "Credit account",
    paymentMethod: "Jane B. • 0330",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "20",
    date: new Date("2025-05-24T12:00:00"),
    merchant: "The Plant Organic Cafe",
    amount: -14.21,
    account: "Ops / Payroll",
    paymentMethod: "Jane B. • 4928",
    icon: "P",
    iconBg: "#dcfce7",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "21",
    date: new Date("2025-05-24T10:30:00"),
    merchant: "To Ops / Payroll",
    amount: -54810.16,
    account: "AR",
    paymentMethod: "Transfer",
    icon: "$",
    iconBg: "#f3f4f6",
    type: "transfer" as const,
    currency: "USD",
  },
  {
    id: "22",
    date: new Date("2025-05-24T14:45:00"),
    merchant: "From AR",
    amount: 54810.16,
    account: "Ops / Payroll",
    paymentMethod: "Transfer",
    icon: "$",
    iconBg: "#f3f4f6",
    type: "transfer" as const,
    currency: "USD",
  },
  // Remaining records - Jumbled
  {
    id: "23",
    date: new Date("2025-05-21T09:15:00"),
    merchant: "Lily's Eatery",
    amount: 0.93,
    account: "Ops / Payroll",
    paymentMethod: "Jane B. • 1234",
    icon: "LE",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "24",
    date: new Date("2025-05-21T16:00:00"),
    merchant: "Deli 77",
    amount: 6.91,
    account: "Credit account",
    paymentMethod: "Jane B. • 5555",
    icon: "D7",
    iconBg: "#e9d5ff",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "25",
    date: new Date("2025-05-21T17:30:00"),
    merchant: "Deli 77",
    amount: 23.28,
    account: "Ops / Payroll",
    paymentMethod: "Landon S. • 4923",
    icon: "D7",
    iconBg: "#e9d5ff",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "26",
    date: new Date("2025-05-21T11:00:00"),
    merchant: "Office Stop Co.",
    amount: -287.89,
    account: "Ops / Payroll",
    paymentMethod: "Jessica A. • 9921",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "27",
    date: new Date("2025-05-21T13:00:00"),
    merchant: "Trader John's",
    amount: 53.49,
    account: "Credit account",
    paymentMethod: "Landon S. • 0331",
    icon: "TJ",
    iconBg: "#fee2e2",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "28",
    date: new Date("2025-05-21T15:30:00"),
    merchant: "Office Stop Co.",
    amount: -662.7,
    account: "Credit account",
    paymentMethod: "Jane B. • 0330",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "29",
    date: new Date("2025-05-21T17:00:00"),
    merchant: "Office Stop Co.",
    amount: 563.94,
    account: "Credit account",
    paymentMethod: "Jane B. • 0330",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "30",
    date: new Date("2025-05-21T12:00:00"),
    merchant: "The Plant Organic Cafe",
    amount: -14.21,
    account: "Ops / Payroll",
    paymentMethod: "Jane B. • 4928",
    icon: "P",
    iconBg: "#dcfce7",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "31",
    date: new Date("2025-05-21T10:30:00"),
    merchant: "To Ops / Payroll",
    amount: -54810.16,
    account: "AR",
    paymentMethod: "Transfer",
    icon: "$",
    iconBg: "#f3f4f6",
    type: "transfer" as const,
    currency: "USD",
  },
  {
    id: "32",
    date: new Date("2025-05-21T14:45:00"),
    merchant: "From AR",
    amount: 54810.16,
    account: "Ops / Payroll",
    paymentMethod: "Transfer",
    icon: "$",
    iconBg: "#f3f4f6",
    type: "transfer" as const,
    currency: "USD",
  },
  {
    id: "33",
    date: new Date("2025-05-29T09:15:00"),
    merchant: "Lily's Eatery",
    amount: 0.93,
    account: "Ops / Payroll",
    paymentMethod: "Jane B. • 1234",
    icon: "LE",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "34",
    date: new Date("2025-05-29T16:00:00"),
    merchant: "Deli 77",
    amount: 6.91,
    account: "Credit account",
    paymentMethod: "Jane B. • 5555",
    icon: "D7",
    iconBg: "#e9d5ff",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "35",
    date: new Date("2025-05-29T17:30:00"),
    merchant: "Deli 77",
    amount: 23.28,
    account: "Ops / Payroll",
    paymentMethod: "Landon S. • 4923",
    icon: "D7",
    iconBg: "#e9d5ff",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "36",
    date: new Date("2025-05-29T11:00:00"),
    merchant: "Office Stop Co.",
    amount: -287.89,
    account: "Ops / Payroll",
    paymentMethod: "Jessica A. • 9921",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "37",
    date: new Date("2025-05-29T13:00:00"),
    merchant: "Trader John's",
    amount: 53.49,
    account: "Credit account",
    paymentMethod: "Landon S. • 0331",
    icon: "TJ",
    iconBg: "#fee2e2",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "38",
    date: new Date("2025-05-21T15:30:00"),
    merchant: "Office Stop Co.",
    amount: -662.7,
    account: "Credit account",
    paymentMethod: "Jane B. • 0330",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "39",
    date: new Date("2025-05-22T17:00:00"),
    merchant: "Office Stop Co.",
    amount: 563.94,
    account: "Credit account",
    paymentMethod: "Jane B. • 0330",
    icon: "OS",
    iconBg: "#dbeafe",
    type: "payment" as const,
    currency: "USD",
  },
  {
    id: "40",
    date: new Date("2025-05-24T12:00:00"),
    merchant: "The Plant Organic Cafe",
    amount: -14.21,
    account: "Ops / Payroll",
    paymentMethod: "Jane B. • 4928",
    icon: "P",
    iconBg: "#dcfce7",
    type: "payment" as const,
    currency: "USD",
  }
];


